import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillMail, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import avatar from "../public/avatar.png";
import profile from "../public/hi-me.png";
import scrum from "../public/scrum.png";
import react from "../public/react.png";
import scfund from "../public/csf.png";
import web1 from "../public/web1.jpg";
import web2 from "../public/web2.jpg";
import web3 from "../public/web3.jpg";
import web4 from "../public/web4.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Arialdys Calderon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <div className=" relative bg-gradient-to-r from-blue-800 to-cyan-400 w-16 h-16 p-0.5 rounded-full overflow-hidden md: w-16 md: h-16">
              <Image src={avatar} className="rounded-full" objectFit="cover" />
            </div>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl dark:text-white"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-blue-800 to-cyan-400 text-white px-4 py-2 rounded-md ml-8"
                  download
                  href="Arialdys_Calderon - Resume.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-5xl py-1 text-blue-800 font-medium md:text-6xl dark:text-white">
              Arialdys Calderon
            </h2>
            <h3 className="text-2xl py-1 text-gray-900 md:text-3xl  dark:text-white">
              <span className=" text-blue-600 dark:text-cyan-500">
                Developer
              </span>{" "}
              / <span className=" text-red-400">Software Tester</span>
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-lg max-w-xl mx-auto dark:text-white">
              I am an adaptable and quick learner person, passionate about
              software development and looking forward to contribute with my
              knowledge and willing to learn more.{" "}
              <span className="text-yellow-500">JavaScript</span>,{" "}
              <span className="text-cyan-500">React</span>,
              <span className="text-orange-500">HTML</span>,{" "}
              <span className="text-blue-500">CSS</span>,{" "}
              <span className="text-red-500">JAVA</span>,
              <span className="text-yellow-600">SQL</span>,{" "}
              <span className="text-orange-500">GIT</span>, are some of the
              tools on my belt, including but not limited to more than 3 years
              performing functional testing.
            </p>
          </div>

          <div className=" text-6xl flex justify-center gap-5 text-blue-500">
            <a href="https://www.linkedin.com/in/arialdyscv/" target="blank">
              <AiFillLinkedin />
            </a>
            <a target="blank" href="mailto:arialdyscv@gmail.com">
              <AiFillMail />
            </a>
            <a target="blank" href="https://github.com/arialdyscv">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-blue-500 rounded-full w-40 h-40 mt-6 overflow-hidden md:h-56 md:w-56">
            <Image src={profile} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div className="lg:flex gap-10 justify-center">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:border-2 border-blue-500">
              <Image src={scrum} width={100} height={100} />
              <h3 className="py-4 text-blue-600 font-bold">
                Certified Scrum Developer
              </h3>
              <h4 className="text-orange-600 font-bold">CertifPro</h4>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:border-2 border-blue-500">
              <Image src={react} width={100} height={100} />
              <h3 className="py-4 text-blue-600 font-bold">React Developer</h3>
              <h4 className="text-green-600 font-bold">Udemy</h4>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:border-2 border-blue-500 ">
              <Image src={scfund} width={100} height={100} />
              <h3 className="py-4 text-blue-600 font-bold">
                Computer Science Fundamentals
              </h3>
              <h4 className="text-purple-700 font-bold">Kodigo</h4>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="dark:text-white">
              These are some of the personal projects that I have done so far.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <div className=" dark:text-white">
                <a
                  href="https://calculator-app-cs3o.onrender.com"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={web1}
                    className="rounded-lg object-cover w-100% h-100%"
                  />
                </a>
                Calculator-app
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className=" dark:text-white">
                <a
                  href="https://indecision-app-zlp9.onrender.com"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={web2}
                    className="rounded-lg object-cover w-100% h-100%"
                  />
                </a>
                Indecision-app
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className=" dark:text-white">
                <a
                  href="https://expensy-app.netlify.app"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={web3}
                    className="rounded-lg object-cover w-100% h-100%"
                  />
                </a>
                Expensify-app
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className=" dark:text-white">
                <a
                  href="https://github.com/arialdyscv/-React-ecommerce-class-components"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={web4}
                    className="rounded-lg object-cover w-100% h-100%"
                  />
                </a>
                eCommerce
              </div>
            </div>
            {/* <div className="basis-1/3 flex-1">
              <div>
                <Image
                  src={web5}
                  className="rounded-lg object-cover w-100% h-100%"
                />
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div>
                <Image
                  src={web5}
                  className="rounded-lg object-cover w-100% h-100%"
                />
              </div>
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
